language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    secure: "j11/eRyuu+bd72o6ev3wB+UKFO6TySH53pAASG4vK6xP7N9S2iMzozPvO2JfZvDHlUqCi67D+GzdXZHw2lsUV+0oDHvaDed8Dh4vNYPHr9hBFbzPl9XXWp8UQ43mybOlh/GVMjDSNC77qpVlGKcCrQ8LzUbt44wBqrBz9u+9yjD4xWL+9HDsu8q87Owgy8scujEfebcvN4rLCklr9Y8JeoeCDhBKIZ10JySVulLDPwlI83i+R6m+v67a64eHh113KkfJ3BgsMCzVN6AvsH679FfgLm5u8hXUU1NWjpfokINjxZ5jDXYa+iyU7EmukHWazKuKkwM7KgUlOFxxPusQTINfv0xgEQySTbV9X1I6QnkNag03GUwS2fnVjlfFdL1az9pADxuzN4lra7kmIQ9NYMqc4/6/ZhT6lIX7hBuWbIXtFiLmfpuMbotpm/ktaUR0ajOqpKnR8xApmhBsZ4CyXoGXuIXOpKzZ0l/snwkOy6Vct+YVf+Mthqk35UNwHWebvEdFcfBthKatkIVes8P3H7ZE1eRKv4u8RTEiqZ+PuRAlpQ7j3EaCa/EszGHHItM/hfrBkmG/6xi5NSypV9KS5hvnOYt5TtCyT+oqVw8y9O6KToQFxN9sYghXnBpdxudj1CxOtFrW9Rz78I9mTKFAZoeK+BXBTJqE1JTRtp2Rnxg="
  secret_access_key:
    secure: "vRm/yVw7nQpaKPGo5HY3hYCt4R5NiHUZbAR7wBC8r9k+pVZzdHmESmEJ5lQqUpi2theZZhthiL2Z4s26d6pt6/FXAqRnFTxdoGhtRCB4FEcCiZrhz0zG852UWHAWqabe6BZ7VCxbVDuMSJMB/dom1wjkt/dpei+qTkmQOAiam5JFMfPwG8Y7kBAhHfShj9Ot/G+VeM+c/9F5n5I4xxD6Xf6GWO3pvYU+5WBXMfEdz2jNf/uC/Zis9Y0kmEd6ehpU8puzS8X8LG72sI8iIpyVmNuUp4HQUyYcTCKspxy5L7tmUKEJNpqJ3Uu+GPOjYwuSytuli/IkoC++QbWdu+z7CP7eQ3kpbUAhlds09BcfMGZx8dK1LOR7RlqJGJnPtDzefL7N+dcajc0lkaZY1UVsgUlU9RwHPkH4ZkVudx+87WPKMkT7rksvz8Uoxog0OU7SmMCfSCUXG9Gz34ainxambc9cP/sMVl6VvJT81Vy27MlsrqUiaYmASfhIqEKzHBbR43VIw0Nj3ZjXMO2HFuo8jlmrTVM4EXXp4flpwoXlZ3Yq0D4h1tFDL8gUJ/q8eV1y/6Sgo+LYlLKPXIwQ4M2VF4qDkRSNG+d4nEo2t141onFVTgMXuZCqtiqGM3LuYOTSRzyWylzTnxSxqF3FmadC9Dbuv4HZxbNnHKABhk9lt1o="
  region: us-east-1
  app: BridgeWorkerPlatform
  env:
    develop: Bridge-WorkerPlatform-dev
    uat: Bridge-WorkerPlatform-uat
    prod: Bridge-WorkerPlatform-prod
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/BridgeWorkerPlatform-1.0.war
  on:
    all_branches: true