language: java
jdk:
- oraclejdk8
sudo: false
before_deploy: mvn clean verify
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAJ6YWVFOX3GHDXVRQ
  secret_access_key:
    secure: "mY1OLSrYrXkoe9JKAJlrGZGq/4JY+4l/5TDhYBK0a2o9/37VQQ+3iTgAEPoZoCpbR/FGzrrFWwfVHPVXQKSjywr16wZ9xMpFiTo9zywYL+fR4kHMJqDc8A9Jvcp6RTsdMAxdHTSwbk4c9bE2l0zxEMlptEKzB1A2bD1FdpxsBAO0pm2SwieW0WL8btj804m7eG7V6Oloo/WR6dkCuCl/RZP9D0dU9NNdYqHujle9G/jFC88XnUUvKXePJ7C0gb41+jIKlZpeE0vK9EF1tQ1KBPdjTALQYdCAWxvA10jALINH8ldklgfThGqdUs+WByYU87onOR3xx4VSW7DNsjRJ4StLElgQ5DO3slmjtliBxY9QYdWHj3tV27sajpac+ha/7BiPGDCjsFsidABZCNVlIGTcZNsgzQ7kUtNZrpmKAlKo8kr0joE8imI/meEi1HS1dB/0/z6L6mO4e2XmaRql+2mV2L2GV8lNulPGuysBY4BMC0ws2qQr0EOR198QF5AOmqjEvvzDG4q37aTllHEP2I+tOrws9N3YnJ4dQpR8tkTjI98yH2ShaeM814mVMETSEvHGJ79+/EoTG8EJQwFBfEluGNr612AfhfY+CxRIEfza41rKYKKTRSi9QGpVoQrl3eGqYRZDBGGlGOJYcT3Nqkv6UZ/UNWTlJHd54kq31Ns="
  region: us-east-1
  app: Bridge-WorkerPlatform
  env:
    develop: Bridge-WorkerPlatform-dev
    uat: Bridge-WorkerPlatform-uat
    prod: Bridge-WorkerPlatform-prod
  bucket_name: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/BridgeWorkerPlatform-1.0.war
  on:
    all_branches: true
