language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
branches:
  only:
  - develop
  - prod
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id: AKIAVRUVU4V5WBQ5J3PQ
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: bridgeworker-$TRAVIS_BRANCH-application
  env: bridgeworker-$TRAVIS_BRANCH
  bucket_name:
    develop: org-biaffectbridge-bridgeserver2-deployment-develop
    prod: org-biaffectbridge-bridgeserver2-deployment-prod
  zip-file: target/BridgeWorkerPlatform-1.0.war
  on:
    all_branches: true
