language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
branches:
  only:
  - develop
  - uat
  - prod
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    develop: AKIAJQOD25TNB4GR4LFQ
    uat: AKIAJQOD25TNB4GR4LFQ
    prod: AKIAZOKKB636GOXML5BE
  secret_access_key:
    develop:
      secure: "ClSlAye7CsoKn0uUC3wTZkQddtF/0ni70B/wOLl0hYhBffLK4Br4OluSNkyZKAKI117PwCmWeR3jetDZFGEZKnAF/MY6t57/m9W77XMj6E/f2NDFT5sbwqnauAL4LM/SFCYdj/rVVAbp0GYfo5D5pgpXJHuNrMVg8KyrOYhLSiIvMNGHvTwdQ4Q8f8XuBfGixG50qaeSinDZYLc70y/wKOS5RW1kvX56aikwIEj7kkMT0vfD4x5Q+G9ZXv5oQAbXqc2VSL/CmkKNRwYs2gJwW3vluEOHQptZrZ+BAiBlOCsfO5lr6dJcPNE9n+asDGceMXb6wNYY1m0im22xGieaxo8Y1zixM/CZIWnEQ3FZ1PnZWF3K0rto8LXz9aMVnhl+T0vG5Qwoz2b0zByMxqr/7rSMJMYPKm1ixvRKIfKlAhcSlVciPkqAC1tfIZu9XqQFlRQWZ7djvyYm1MI1igg/Y/14UHRaPL6LmxopgAY6kGh89WlNcKOoDpeodAZEN1cygwsVR+GIn7/hOeL6fkvLiMMr2vRv18EUctb90F+CTy993UHasW2ExUV3u8AJrWT5Wyzk/IH0Byyta19xRPK0uAwGOdIqt5WNOm5FJAQqXdTtw1phfjnidCFYlNW4gGcR1pvB/ddVBPk83uBnT2o4HkTI4jZe3Dxro87owaqWbMQ="
    uat:
      secure: "ClSlAye7CsoKn0uUC3wTZkQddtF/0ni70B/wOLl0hYhBffLK4Br4OluSNkyZKAKI117PwCmWeR3jetDZFGEZKnAF/MY6t57/m9W77XMj6E/f2NDFT5sbwqnauAL4LM/SFCYdj/rVVAbp0GYfo5D5pgpXJHuNrMVg8KyrOYhLSiIvMNGHvTwdQ4Q8f8XuBfGixG50qaeSinDZYLc70y/wKOS5RW1kvX56aikwIEj7kkMT0vfD4x5Q+G9ZXv5oQAbXqc2VSL/CmkKNRwYs2gJwW3vluEOHQptZrZ+BAiBlOCsfO5lr6dJcPNE9n+asDGceMXb6wNYY1m0im22xGieaxo8Y1zixM/CZIWnEQ3FZ1PnZWF3K0rto8LXz9aMVnhl+T0vG5Qwoz2b0zByMxqr/7rSMJMYPKm1ixvRKIfKlAhcSlVciPkqAC1tfIZu9XqQFlRQWZ7djvyYm1MI1igg/Y/14UHRaPL6LmxopgAY6kGh89WlNcKOoDpeodAZEN1cygwsVR+GIn7/hOeL6fkvLiMMr2vRv18EUctb90F+CTy993UHasW2ExUV3u8AJrWT5Wyzk/IH0Byyta19xRPK0uAwGOdIqt5WNOm5FJAQqXdTtw1phfjnidCFYlNW4gGcR1pvB/ddVBPk83uBnT2o4HkTI4jZe3Dxro87owaqWbMQ="
    prod:
      secure: "m8oOdVZp2AqPsOBmHRQGmiEh1Mhao6XBqj8WC28xUQqth49304wZVf9F1DrEQWAem8r2maAb0A1TI4vb6I9jPRyqV94BCjcJy+jZdiCeNrDCPl6SKNmp0edwZeocXQv8ya9UdozXvRW6tTlWt0muquYPdpWD4dgM6iO5qf+S/WptrCkqr6Ar4y2Ag6A9ltNybaCZLki1VrLzK+Gky1xLMR5YbA8l6ZLcULipCzp1v3ktGkepppxdiikCu0K7kp9xhwymBo9l091VWA4TMXtgx6+FCIC2Rbd3qrAG1EmpJuQk8+4FPa9YgVgLa5SKX6zYxUz5yiGS9+mKSyETcudm/9bJt9Y9WQczL8Lq7C3+fx74MoUMj2lMV0kStVXsV34e6HGbFEuuKPWrjF/5yVHcImb7zcwX7/NiuDCWNH4COb+q0gCYoGK2k+9rWhBbVdDsfL1bFAwEEOB61yRHBVVL+UPU839U/8+ZWPd9B32Ugz4LpUY8ONwPojgerraEY+WdT2qQ6BLq82qmDaU28vM8fbWxWoJDMeQBda3CnDAHZKx/1epZeXn1S2Bq9DsoD0whrtbFBS5gESL5J6nI0SpwgbXzOK2UQmJ3D3jCQdFfkI8v43bpQnSiBi+l7EIXYZbOPBzTEWgSKD5fcKuu8iweGIe01OHYbY5HqyE5W1tBCfE="
  region: us-east-1
  app: bridgeworker-$TRAVIS_BRANCH-application
  env: bridgeworker-$TRAVIS_BRANCH
  bucket_name:
    develop: elasticbeanstalk-us-east-1-420786776710
    uat: elasticbeanstalk-us-east-1-420786776710
    prod: elasticbeanstalk-us-east-1-649232250620
  zip-file: target/BridgeWorkerPlatform-1.0.war
  on:
    all_branches: true
